### PR TITLE
stopgap solution for smart contract payouts

### PR DESCRIPTION
**Pull request by nicolasochem**
New Defi smart contracts such as Kolibri have expensive payout
operations. Backerei fee/storage/gas parameters for payout operations
are hardcoded in values that are too low for payouts to work.

This results in "simulation failure" whenever someone delegates
a Kolibri smart contract to your baker.

This PR fixes it in a very crude way, by setting high limits and fees
to every smart contract, and the usual low fee to tz addresses.

It will probably fail when there are too many Kolibri delegators
attached to your baker. Backerei has a mechanism to split payouts
across several blocks, but it does not take this new change into
account.

This should be replaced by a mechanism to estimate the fee for
every payout and charge it back to the delegator.

I don't think anyone will take that on, so the actual recommendation
is to switch to maintained payout software such as TRD.

May I have merge permissions for this repository as well?

### CODE REVIEW

**Review by cwgoes — APPROVED** [review]
ACK

**Comment by cwgoes** [comment]
@nicolasochem Thanks for the contribution. Yes, as Cryptium Labs is shutting down, `backerei` will no longer be actively maintained. Would you like to take over maintenance of the software? Happy to transfer the repository or change permissions if you're interested.

**Comment by nicolasochem** [comment]
Yes please transfer to midl_dev org.

**Comment by cwgoes** [comment]
> midl_dev

I can't see that (https://github.com/midl_dev ?), is it private?

**Comment by nicolasochem** [comment]
sorry, `midl-dev`

**Comment by cwgoes** [comment]
> sorry, `midl-dev`

Thanks, I need to check before transferring, I've added you with maintain access just now as well.

**Pull request merged**
